---

image: archlinux
packages:
  - gtk3
  - jq
  - make
  - nerd-fonts
  - python-pip
  - resume-pycli
  - wkhtmltopdf
oauth: pages.sr.ht/PAGES:RW
environment:
  PATH: /home/build/.local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  site: cv.karolak.fr
tasks:
  - build: |
      cd cv
      make build
  - upload: |
      cd cv
      acurl -f https://pages.sr.ht/publish/$site -F content=@site.tar.gz
