---

image: archlinux
packages:
  - gtk3
  - make
  - python-pip
  - wkhtmltopdf
oauth: pages.sr.ht/PAGES:RW
triggers:
  - action: email
    condition: always
    to: Nicolas Karolak <nicolas@karolak.fr>
environment:
  PATH: /home/build/.local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  site: cv.karolak.fr
tasks:
  - setup: |
      cd cv
      make setup
  - build: |
      cd cv
      make build
  - upload: |
      cd cv
      acurl -f https://pages.sr.ht/publish/$site -F content=@site.tar.gz
