---

defaultContentLanguage: fr
disableKinds:
  - RSS
  - section
  - sitemap
  - taxonomy
  - term
languages:
  en:
    flag: 🇬🇧
    languageName: English
  fr:
    flag: 🇫🇷
    languageName: Français
theme: simple
