[build]
publish = "public/"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; base-uri 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; form-action 'none'; frame-ancestors 'none'"
Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
