version: '3'

set: [errexit, nounset, pipefail]
shopt: [globstar]

includes:
  lint:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/lint.yml
    internal: true
  format:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/format.yml
    internal: true

tasks:
  init:
    desc: Initialize repositry
    cmds:
      - git config core.hooksPath .githooks
      - git config commit.template .gitmessage

  lint:
    desc: Run linters
    cmds:
      - task: lint:default

  format:
    desc: Run formatters
    cmds:
      - task: format:default

  serve:
    desc: Run Hugo local development server
    cmd: hugo serve

  build-dev:
    desc: Build development website
    vars:
      BASE_URL:
        sh: echo "${BASE_URL:-/}"
    cmd: hugo --buildDrafts --buildFuture --gc --baseURL "{{.BASE_URL}}"

  build:
    desc: Build website
    vars:
      BASE_URL:
        sh: echo "${BASE_URL:-/}"
    cmd: hugo --gc --minify --baseURL "{{.BASE_URL}}"

  clean:
    desc: Cleanup build files
    cmds:
      - rm -rf ./public/
