name: Deploy Hugo site to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "netlify"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: 1.21.5
  # renovate: datasource=github-releases depName=gohugoio/hugo
  HUGO_VERSION: v0.121.1
  # renovate: datasource=npm depName=netlify-cli
  NETLIFY_VERSION: 17.10.2

jobs:
  netlify:
    runs-on: ubuntu-22.04
    environment:
      name: netlify
      url: ${{ fromJSON(steps.deploy.outputs.json).url }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./.github/workflows/cd.yml

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@${{ env.HUGO_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          cache: npm
          cache-dependency-path: ./.github/workflows/cd.yml

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@${{ env.NETLIFY_VERSION }}

      - name: Build with Hugo
        run: hugo --gc --minify

      - name: Deploy to Netlify
        id: deploy
        run: echo "json=$(netlify deploy --dir ./public --prod --json | jq -c)" >> "$GITHUB_OUTPUT"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
