name: Deploy Hugo site to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "netlify"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: 1.21.4
  # renovate: datasource=github-releases depName=gohugoio/hugo
  HUGO_VERSION: v0.120.4
  # renovate: datasource=npm depName=netlify-cli
  NETLIFY_VERSION: 17.6.0

jobs:
  netlify:
    runs-on: ubuntu-22.04
    environment:
      name: netlify
      url: ${{ fromJSON(steps.deploy.outputs.json).url }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./.github/workflows/cd.yml

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@${{ env.HUGO_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          cache: npm
          cache-dependency-path: ./.github/workflows/cd.yml

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@${{ env.NETLIFY_VERSION }}

      - name: Build with Hugo
        run: hugo --gc --minify

      - name: Deploy to Netlify
        id: deploy
        run: echo "json=$(netlify deploy --dir ./public --prod --json | jq -c)" >> "$GITHUB_OUTPUT"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
