name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          /home/linuxbrew/.linuxbrew/bin/brew install \
            actionlint \
            check-jsonschema \
            yamlfmt \
            yamllint \

      - name: Lint
        run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          /home/linuxbrew/.linuxbrew/bin/brew install \
            hugo \

      - name: Build
        run: make build-dev
