name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@e77a13149bd439f1dce6e1ab7eee379855f71a0e # 1.6.1

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@latest

      - name: Build with Hugo
        run: hugo --buildDrafts --buildFuture
