name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: ghcr.io/nikaro/gha:latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Lint
        run: task lint --yes

  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/nikaro/gha:latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install hugo
        run: brew install hugo

      - name: Build
        run: task build-dev --yes

  check:
    name: Check
    permissions: {}
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: always()
    steps:
      - name: Ensure no jobs failed
        run: |-
          [ "${{ !contains(needs.*.result, 'failure') }}" = "true" ] || exit 1
