---
name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@09f4303c25301bd9306525d3989a9f0ed938ad2f # 1.6.6
        with:
          python-version: 3.x

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@latest

      - name: Build with Hugo
        run: hugo --buildDrafts --buildFuture
