name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: 1.22.1
  # renovate: datasource=github-releases depName=gohugoio/hugo
  HUGO_VERSION: v0.124.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@988ef9aa9dc1731203ea6c6ada2f7a53a86271d5 # 1.3.19

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./.github/workflows/ci.yml

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@${{ env.HUGO_VERSION }}

      - name: Build with Hugo
        run: hugo --buildDrafts --buildFuture
