name: Deploy Hugo site to Pages

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo CLI
        uses: peaceiris/actions-hugo@v2.6.0

      - name: Build with Hugo
        run: hugo --gc --minify
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: github.ref_name == 'main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
